### ISSUE TITLE
documentation: add namespaces REST API to swagger docs

### ISSUE THREAD

**Issue by mena-bosch** [eclipse/vorto#2266]
Parked until pre-requisites met. 

**Pre-requisites**

- [ ] #2152 finalized
- [ ] #2265 finalized
- [ ] agreement with team that namespaces REST API is stable and can be moved to API V1

**Task**
- [ ] Move API paths from `/rest/...` to `/api/v1/namespaces`
- [ ] Document in `vorto_repository-1.0.yml`
